# start from a clean base image (replace <version> with the desired release)
# FROM runpod/worker-comfyui:5.4.1-base

# Use temporary custom development image. 
# See https://github.com/Shellishack/worker-comfyui
FROM shellishack/worker-comfyui:dev

# install remote media loader nodes
RUN comfy node install comfyui_remote_media_io

# install custom node dependencies
RUN cd /comfyui/custom_nodes/comfyui_remote_media_io && \
    pip install .[dev]
